-- PostgreSQL Database Schema for Psikonutrisense
-- Database: psikonutrisense_db
--
-- NOTE: as of 2026-09-21, schema changes are made via Laravel migrations
-- (backend/database/migrations/). This file is kept as a human-readable
-- reference of the full schema, regenerated by hand to match the migrations
-- (no pg_dump available in this environment) — always cross-check against
-- `php artisan migrate:status` / the migrations folder if in doubt.

DROP TABLE IF EXISTS main_goals CASCADE;
DROP TABLE IF EXISTS health_conditions CASCADE;
DROP TABLE IF EXISTS favorite_local_foods CASCADE;
DROP TABLE IF EXISTS food_group_frequencies CASCADE;
DROP TABLE IF EXISTS local_recipes CASCADE;
DROP TABLE IF EXISTS sanitation_facilities CASCADE;
DROP TABLE IF EXISTS mother_wellbeing_screenings CASCADE;
DROP TABLE IF EXISTS pmt_logs CASCADE;
DROP TABLE IF EXISTS nutrition_records CASCADE;
DROP TABLE IF EXISTS vaccination_records CASCADE;
DROP TABLE IF EXISTS growth_records CASCADE;
DROP TABLE IF EXISTS children CASCADE;
DROP TABLE IF EXISTS mothers CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS personal_access_tokens CASCADE;

-- 1. Users Table
CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'ibu',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 1b. Personal Access Tokens (Laravel Sanctum, auto-migrated by the package)
CREATE TABLE personal_access_tokens (
    id BIGSERIAL PRIMARY KEY,
    tokenable_type VARCHAR(255) NOT NULL,
    tokenable_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    token VARCHAR(64) UNIQUE NOT NULL,
    abilities TEXT NULL,
    last_used_at TIMESTAMP NULL,
    expires_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Mothers Table (Modul A & E)
CREATE TABLE mothers (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    nama_ibu VARCHAR(255) NOT NULL,
    nik_ibu VARCHAR(16) UNIQUE NOT NULL,
    tanggal_lahir_ibu DATE NOT NULL,
    pendidikan_terakhir VARCHAR(50) NOT NULL,
    pekerjaan VARCHAR(100) NOT NULL,
    alamat_dusun_rt_rw VARCHAR(255) NOT NULL,
    no_hp_whatsapp VARCHAR(20) NOT NULL,
    foto_buku_kia VARCHAR(255) NULL,
    poin_ibu_aktif INT DEFAULT 1250,
    lencana_aktif BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Children Table (Modul A)
CREATE TABLE children (
    id BIGSERIAL PRIMARY KEY,
    mother_id BIGINT NOT NULL REFERENCES mothers(id) ON DELETE CASCADE,
    nama_balita VARCHAR(255) NOT NULL,
    tanggal_lahir_balita DATE NOT NULL,
    jenis_kelamin VARCHAR(1) NOT NULL CHECK (jenis_kelamin IN ('L', 'P')),
    anak_ke INT NOT NULL DEFAULT 1,
    jumlah_saudara INT NOT NULL DEFAULT 0,
    bb_lahir_kg NUMERIC(4,2) NULL,
    pb_lahir_cm NUMERIC(4,2) NULL,
    lahir_prematur BOOLEAN DEFAULT FALSE,
    jenis_persalinan VARCHAR(20) NULL,          -- 'Normal' | 'Caesar' (desain #10, dipindah dari form antropometri)
    usia_kehamilan_minggu INT NULL,             -- mis. 39 (desain #10)
    status_kepemilikan_kia BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Growth Records Table (Modul B - Antropometri & Kurva WHO)
CREATE TABLE growth_records (
    id BIGSERIAL PRIMARY KEY,
    child_id BIGINT NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    tanggal_penimbangan DATE NOT NULL,
    berat_badan_kg NUMERIC(4,2) NOT NULL,
    tinggi_badan_cm NUMERIC(4,2) NOT NULL,
    lingkar_kepala_cm NUMERIC(4,2) NOT NULL,
    lila_cm NUMERIC(4,2) NOT NULL,
    status_penimbangan VARCHAR(50) DEFAULT 'Naik',
    status_gizi VARCHAR(50) DEFAULT 'Normal',
    zscore_bbu NUMERIC(4,2) DEFAULT 0.20,
    zscore_tbu NUMERIC(4,2) DEFAULT 0.10,
    kpsp_checklist_json JSONB NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. Vaccination Records Table (Modul C - Imunisasi Buku KIA)
CREATE TABLE vaccination_records (
    id BIGSERIAL PRIMARY KEY,
    child_id BIGINT NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    jenis_imunisasi VARCHAR(100) NOT NULL,
    tanggal_jadwal DATE NOT NULL,
    tanggal_pemberian DATE NULL,
    status VARCHAR(50) DEFAULT 'Belum' CHECK (status IN ('Sudah', 'Belum', 'Mendekati', 'Terlambat')),
    alasan_belum TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Nutrition Records Table (Modul D - Menyusui & MPASI, desain #13)
CREATE TABLE nutrition_records (
    id BIGSERIAL PRIMARY KEY,
    child_id BIGINT NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    asi_eksklusif BOOLEAN DEFAULT TRUE,
    masih_menyusui BOOLEAN DEFAULT TRUE,
    usia_mulai_mpasi_bulan INT NOT NULL DEFAULT 6,
    jenis_mpasi_json JSONB NULL,                -- ["Bubur Tim","Makanan Lumat","Makanan Keluarga"]
    frekuensi_makan_per_hari INT NOT NULL DEFAULT 3,
    frekuensi_camilan_per_hari INT NOT NULL DEFAULT 0,
    recall_24jam_menu TEXT NULL,
    kendala_pemberian_makan VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6b. Food Group Frequencies Table (Modul D - Asupan Pangan, desain #14)
CREATE TABLE food_group_frequencies (
    id BIGSERIAL PRIMARY KEY,
    child_id BIGINT NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    tanggal_pencatatan DATE NOT NULL,
    nasi_bubur VARCHAR(20) NOT NULL,
    lauk_hewani VARCHAR(20) NOT NULL,
    lauk_nabati VARCHAR(20) NOT NULL,
    sayur VARCHAR(20) NOT NULL,
    buah VARCHAR(20) NOT NULL,
    susu VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6c. Favorite Local Foods Table (Modul D - Pangan Favorit, desain #15)
CREATE TABLE favorite_local_foods (
    id BIGSERIAL PRIMARY KEY,
    child_id BIGINT NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    bahan_json JSONB NOT NULL,                  -- ["Daun Kelor","Jagung","Ubi Jalar",...]
    bahan_lainnya VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6d. Health Conditions Table (Modul B - Kondisi Kesehatan, desain #11)
CREATE TABLE health_conditions (
    id BIGSERIAL PRIMARY KEY,
    child_id BIGINT NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    pernah_dirawat_rs BOOLEAN DEFAULT FALSE,
    sering_sakit_3bulan BOOLEAN DEFAULT FALSE,
    alergi_makanan_obat BOOLEAN DEFAULT FALSE,
    keterangan_alergi VARCHAR(255) NULL,
    status_imunisasi_ringkasan VARCHAR(30) DEFAULT 'Lengkap',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. PMT Logs Table (Modul D - Modul Harian PMT)
CREATE TABLE pmt_logs (
    id BIGSERIAL PRIMARY KEY,
    child_id BIGINT NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    tanggal DATE NOT NULL,
    status_konsumsi VARCHAR(50) NOT NULL CHECK (status_konsumsi IN ('Habis', 'Sebagian', 'Tidak')),
    qr_code_scanned VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8. Mother Wellbeing Screenings Table (Modul E - Kondisi Psikososial, desain #17 & #18)
CREATE TABLE mother_wellbeing_screenings (
    id BIGSERIAL PRIMARY KEY,
    mother_id BIGINT NOT NULL REFERENCES mothers(id) ON DELETE CASCADE,
    frekuensi_interaksi_bermain INT CHECK (frekuensi_interaksi_bermain BETWEEN 1 AND 5),
    pengasuh_utama VARCHAR(100) DEFAULT 'Ibu Kandung',
    -- desain #17: 4 item skala 0-4 (bukan skor gabungan)
    skor_cemas_berlebihan SMALLINT CHECK (skor_cemas_berlebihan BETWEEN 0 AND 4),
    skor_mudah_lelah SMALLINT CHECK (skor_mudah_lelah BETWEEN 0 AND 4),
    skor_sedih_tanpa_sebab SMALLINT CHECK (skor_sedih_tanpa_sebab BETWEEN 0 AND 4),
    skor_didukung_keluarga_umum SMALLINT CHECK (skor_didukung_keluarga_umum BETWEEN 0 AND 4),
    -- desain #18: dukungan keluarga dirinci 3 dimensi, skala 0-4
    dukungan_emosional SMALLINT CHECK (dukungan_emosional BETWEEN 0 AND 4),
    dukungan_informasi SMALLINT CHECK (dukungan_informasi BETWEEN 0 AND 4),
    dukungan_praktis SMALLINT CHECK (dukungan_praktis BETWEEN 0 AND 4),
    kategori_kesejahteraan VARCHAR(100) DEFAULT 'Tenang & Bahagia',
    cukup_informasi_gizi VARCHAR(20) DEFAULT 'Ya',
    sumber_informasi_terpercaya VARCHAR(100) DEFAULT 'Posyandu',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8b. Main Goals Table (Modul E - Tujuan Utama, desain #19)
CREATE TABLE main_goals (
    id BIGSERIAL PRIMARY KEY,
    mother_id BIGINT NOT NULL REFERENCES mothers(id) ON DELETE CASCADE,
    tujuan_utama VARCHAR(100) NOT NULL,
    harapan_untuk_anak TEXT NULL,
    bersedia_ikut_intervensi BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 9. Sanitation Facilities Table (Modul F - Sanitasi & Akses Layanan)
CREATE TABLE sanitation_facilities (
    id BIGSERIAL PRIMARY KEY,
    mother_id BIGINT NOT NULL REFERENCES mothers(id) ON DELETE CASCADE,
    sumber_air_minum VARCHAR(100) NOT NULL,
    jamban_sehat BOOLEAN DEFAULT TRUE,
    jarak_posyandu_km NUMERIC(4,2) DEFAULT 0.5,
    kepesertaan_bpjs BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 10. Local Recipes Table (Resep Pangan Lokal Ngeposari)
CREATE TABLE local_recipes (
    id BIGSERIAL PRIMARY KEY,
    nama_resep VARCHAR(255) NOT NULL,
    bahan_lokal_utama VARCHAR(255) NOT NULL,
    usia_rekomendasi_bulan VARCHAR(50) NOT NULL,
    deskripsi_gizi TEXT NOT NULL,
    langkah_memasak_json JSONB NOT NULL,
    video_url VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- SEED INITIAL DATA FOR NGEPOSARI
INSERT INTO local_recipes (nama_resep, bahan_lokal_utama, usia_rekomendasi_bulan, deskripsi_gizi, langkah_memasak_json) VALUES 
('Puree Kelor Lele Ngeposari', 'Daun Kelor, Ikan Lele, Telur', '6-8 Bulan', 'Kaya akan Protein Hewani, Zat Besi & Vitamin A untuk mencegah stunting.', '["Kukus ikan lele dan ambil dagingnya tanpa duri", "Rebus daun kelor sebentar", "Haluskan bersama nasi tim dan telur rebus"]'),
('Sup Tim Tempe Telur Kelor', 'Tempe, Telur Ayam, Daun Kelor', '9-11 Bulan', 'Tinggi kalori dan lemak sehat untuk mengoptimalkan BB balita.', '["Cincang halus tempe dan telur", "Tumis dengan sedikit minyak kelapa", "Tambahkan kaldu dan daun kelor cincang"]');
